# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 15:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('duration', models.CharField(blank=True, max_length=50, null=True)),
                ('preview', models.ImageField(blank=True, null=True, upload_to=b'')),
                ('status', models.CharField(blank=True, choices=[(b'loading', '\u0417\u0430\u0433\u0440\u0443\u0436\u0430\u0435\u0442\u0441\u044f'), (b'loaded', '\u0417\u0430\u0433\u0440\u0443\u0436\u0435\u043d'), (b'queued', '\u0412 \u043e\u0447\u0435\u0440\u0435\u0434\u0438'), (b'processing', '\u041e\u0431\u0440\u0430\u0431\u0430\u0442\u044b\u0432\u0430\u0435\u0442\u0441\u044f'), (b'ready', '\u0413\u043e\u0442\u043e\u0432\u043e'), (b'error', '\u041e\u0448\u0438\u0431\u043a\u0430')], max_length=30, null=True)),
                ('video', models.FileField(upload_to=b'')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.Category')),
            ],
        ),
    ]
